// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"
)

type Media struct {
	ID        interface{} `json:"id"`
	Url       string      `json:"url"`
	Title     string      `json:"title"`
	Image     string      `json:"image"`
	ServiceID int64       `json:"service_id"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
	DeletedAt interface{} `json:"deleted_at"`
}

type Service struct {
	ID        interface{}    `json:"id"`
	Name      string         `json:"name"`
	Logo      sql.NullString `json:"logo"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
}
