# .air.toml
root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build -o ./main ."
  bin = "./api"
  delay = 1000 # ms
  exclude_dir = ["assets", "tmp", "vendor"]
  include_ext = ["go", "sql"]
  exclude_regex = ["_test\\.go"]
